# Generated by Django 5.0.1 on 2024-01-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_date2',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
